// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: air_temp_humid_readings.sql

package database

import (
	"context"
	"time"
)

const deleteOldAirTempHumidReadings = `-- name: DeleteOldAirTempHumidReadings :exec
DELETE FROM air_temp_humid_readings WHERE created_at < $1
`

func (q *Queries) DeleteOldAirTempHumidReadings(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldAirTempHumidReadings, createdAt)
	return err
}

const getAirTempHumidReadingsByAddr = `-- name: GetAirTempHumidReadingsByAddr :many
SELECT addr, temperature, humidity, created_at
FROM air_temp_humid_readings
WHERE addr = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetAirTempHumidReadingsByAddrParams struct {
	Addr  int16
	Limit int32
}

type GetAirTempHumidReadingsByAddrRow struct {
	Addr        int16
	Temperature int16
	Humidity    int16
	CreatedAt   time.Time
}

func (q *Queries) GetAirTempHumidReadingsByAddr(ctx context.Context, arg GetAirTempHumidReadingsByAddrParams) ([]GetAirTempHumidReadingsByAddrRow, error) {
	rows, err := q.db.QueryContext(ctx, getAirTempHumidReadingsByAddr, arg.Addr, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAirTempHumidReadingsByAddrRow
	for rows.Next() {
		var i GetAirTempHumidReadingsByAddrRow
		if err := rows.Scan(
			&i.Addr,
			&i.Temperature,
			&i.Humidity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestAirTempHumidReadings = `-- name: GetLatestAirTempHumidReadings :many
SELECT DISTINCT ON (addr)
    addr, temperature, humidity, created_at
FROM air_temp_humid_readings
ORDER BY addr, created_at DESC
`

type GetLatestAirTempHumidReadingsRow struct {
	Addr        int16
	Temperature int16
	Humidity    int16
	CreatedAt   time.Time
}

func (q *Queries) GetLatestAirTempHumidReadings(ctx context.Context) ([]GetLatestAirTempHumidReadingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestAirTempHumidReadings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestAirTempHumidReadingsRow
	for rows.Next() {
		var i GetLatestAirTempHumidReadingsRow
		if err := rows.Scan(
			&i.Addr,
			&i.Temperature,
			&i.Humidity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAirTempHumidReading = `-- name: InsertAirTempHumidReading :exec
INSERT INTO air_temp_humid_readings (addr, temperature, humidity, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertAirTempHumidReadingParams struct {
	Addr        int16
	Temperature int16
	Humidity    int16
	CreatedAt   time.Time
}

func (q *Queries) InsertAirTempHumidReading(ctx context.Context, arg InsertAirTempHumidReadingParams) error {
	_, err := q.db.ExecContext(ctx, insertAirTempHumidReading,
		arg.Addr,
		arg.Temperature,
		arg.Humidity,
		arg.CreatedAt,
	)
	return err
}
