// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package database

import (
	"context"
)

const countContactsByEmailToday = `-- name: CountContactsByEmailToday :one
SELECT COUNT(*) FROM contacts
WHERE email = $1
AND created_at >= CURRENT_DATE
AND created_at < CURRENT_DATE + INTERVAL '1 day'
`

func (q *Queries) CountContactsByEmailToday(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContactsByEmailToday, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContactsByIPToday = `-- name: CountContactsByIPToday :one
SELECT COUNT(*) FROM contacts
WHERE ip_address = $1
AND created_at >= CURRENT_DATE
AND created_at < CURRENT_DATE + INTERVAL '1 day'
`

func (q *Queries) CountContactsByIPToday(ctx context.Context, ipAddress string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContactsByIPToday, ipAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (name, email, subject, message, ip_address)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, subject, message, ip_address, created_at
`

type CreateContactParams struct {
	Name      string
	Email     string
	Subject   string
	Message   string
	IpAddress string
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, createContact,
		arg.Name,
		arg.Email,
		arg.Subject,
		arg.Message,
		arg.IpAddress,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Subject,
		&i.Message,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}
