// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type AirTempHumidReading struct {
	ID          int64
	Addr        int16
	Temperature int16
	Humidity    int16
	CreatedAt   time.Time
}

type Contact struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Subject   string
	Message   string
	IpAddress string
	CreatedAt time.Time
}

type Group struct {
	ID          uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
}

type GroupPermission struct {
	GroupID      uuid.UUID
	PermissionID uuid.UUID
}

type MqttAcl struct {
	ID           uuid.UUID
	CredentialID uuid.UUID
	Topic        string
	Permission   string
	CreatedAt    time.Time
}

type MqttCredential struct {
	ID        uuid.UUID
	Username  string
	Password  string
	CreatedAt time.Time
}

type Permission struct {
	ID          uuid.UUID
	Resource    string
	Action      string
	Description string
	CreatedAt   time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	UserAgent string
	IpAddress string
	CreatedAt time.Time
}

type SoilCalibration struct {
	SensorIdx int16
	DryValue  int16
	WetValue  int16
	UpdatedAt time.Time
}

type SoilMoistureReading struct {
	ID        int64
	SensorIdx int16
	Raw       int16
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserGroup struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}
