// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type Contact struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Subject   string
	Message   string
	IpAddress string
	CreatedAt time.Time
}

type SensorReading struct {
	ID          int64
	Addr        int16
	Temperature int16
	Humidity    int16
	CreatedAt   time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	UserAgent string
	IpAddress string
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
