// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mqtt_credentials.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMQTTACL = `-- name: CreateMQTTACL :one
INSERT INTO mqtt_acl (credential_id, topic, permission)
VALUES ($1, $2, $3)
RETURNING id, credential_id, topic, permission, created_at
`

type CreateMQTTACLParams struct {
	CredentialID uuid.UUID
	Topic        string
	Permission   string
}

func (q *Queries) CreateMQTTACL(ctx context.Context, arg CreateMQTTACLParams) (MqttAcl, error) {
	row := q.db.QueryRowContext(ctx, createMQTTACL, arg.CredentialID, arg.Topic, arg.Permission)
	var i MqttAcl
	err := row.Scan(
		&i.ID,
		&i.CredentialID,
		&i.Topic,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const createMQTTCredential = `-- name: CreateMQTTCredential :one
INSERT INTO mqtt_credentials (username, password)
VALUES ($1, $2)
RETURNING id, username, password, created_at
`

type CreateMQTTCredentialParams struct {
	Username string
	Password string
}

func (q *Queries) CreateMQTTCredential(ctx context.Context, arg CreateMQTTCredentialParams) (MqttCredential, error) {
	row := q.db.QueryRowContext(ctx, createMQTTCredential, arg.Username, arg.Password)
	var i MqttCredential
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getMQTTACLByCredentialID = `-- name: GetMQTTACLByCredentialID :many
SELECT id, credential_id, topic, permission, created_at FROM mqtt_acl WHERE credential_id = $1
`

func (q *Queries) GetMQTTACLByCredentialID(ctx context.Context, credentialID uuid.UUID) ([]MqttAcl, error) {
	rows, err := q.db.QueryContext(ctx, getMQTTACLByCredentialID, credentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MqttAcl
	for rows.Next() {
		var i MqttAcl
		if err := rows.Scan(
			&i.ID,
			&i.CredentialID,
			&i.Topic,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMQTTCredentialByUsername = `-- name: GetMQTTCredentialByUsername :one
SELECT id, username, password, created_at FROM mqtt_credentials WHERE username = $1
`

func (q *Queries) GetMQTTCredentialByUsername(ctx context.Context, username string) (MqttCredential, error) {
	row := q.db.QueryRowContext(ctx, getMQTTCredentialByUsername, username)
	var i MqttCredential
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
