// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sensor_readings.sql

package database

import (
	"context"
	"time"
)

const deleteOldSensorReadings = `-- name: DeleteOldSensorReadings :exec
DELETE FROM sensor_readings WHERE created_at < $1
`

func (q *Queries) DeleteOldSensorReadings(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldSensorReadings, createdAt)
	return err
}

const getLatestReadings = `-- name: GetLatestReadings :many
SELECT DISTINCT ON (addr)
    addr, temperature, humidity, created_at
FROM sensor_readings
ORDER BY addr, created_at DESC
`

type GetLatestReadingsRow struct {
	Addr        int16
	Temperature int16
	Humidity    int16
	CreatedAt   time.Time
}

func (q *Queries) GetLatestReadings(ctx context.Context) ([]GetLatestReadingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestReadings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestReadingsRow
	for rows.Next() {
		var i GetLatestReadingsRow
		if err := rows.Scan(
			&i.Addr,
			&i.Temperature,
			&i.Humidity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadingsByAddr = `-- name: GetReadingsByAddr :many
SELECT addr, temperature, humidity, created_at
FROM sensor_readings
WHERE addr = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetReadingsByAddrParams struct {
	Addr  int16
	Limit int32
}

type GetReadingsByAddrRow struct {
	Addr        int16
	Temperature int16
	Humidity    int16
	CreatedAt   time.Time
}

func (q *Queries) GetReadingsByAddr(ctx context.Context, arg GetReadingsByAddrParams) ([]GetReadingsByAddrRow, error) {
	rows, err := q.db.QueryContext(ctx, getReadingsByAddr, arg.Addr, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReadingsByAddrRow
	for rows.Next() {
		var i GetReadingsByAddrRow
		if err := rows.Scan(
			&i.Addr,
			&i.Temperature,
			&i.Humidity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSensorReading = `-- name: InsertSensorReading :exec
INSERT INTO sensor_readings (addr, temperature, humidity)
VALUES ($1, $2, $3)
`

type InsertSensorReadingParams struct {
	Addr        int16
	Temperature int16
	Humidity    int16
}

func (q *Queries) InsertSensorReading(ctx context.Context, arg InsertSensorReadingParams) error {
	_, err := q.db.ExecContext(ctx, insertSensorReading, arg.Addr, arg.Temperature, arg.Humidity)
	return err
}
