// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: soil_moisture_readings.sql

package database

import (
	"context"
	"time"
)

const deleteOldSoilMoistureReadings = `-- name: DeleteOldSoilMoistureReadings :exec
DELETE FROM soil_moisture_readings WHERE created_at < $1
`

func (q *Queries) DeleteOldSoilMoistureReadings(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldSoilMoistureReadings, createdAt)
	return err
}

const getLatestSoilMoistureReadings = `-- name: GetLatestSoilMoistureReadings :many
SELECT DISTINCT ON (sensor_idx) sensor_idx, raw, created_at
FROM soil_moisture_readings
ORDER BY sensor_idx, created_at DESC
`

type GetLatestSoilMoistureReadingsRow struct {
	SensorIdx int16
	Raw       int16
	CreatedAt time.Time
}

func (q *Queries) GetLatestSoilMoistureReadings(ctx context.Context) ([]GetLatestSoilMoistureReadingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestSoilMoistureReadings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestSoilMoistureReadingsRow
	for rows.Next() {
		var i GetLatestSoilMoistureReadingsRow
		if err := rows.Scan(&i.SensorIdx, &i.Raw, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSoilMoistureReadingsBySensorIdx = `-- name: GetSoilMoistureReadingsBySensorIdx :many
SELECT sensor_idx, raw, created_at
FROM soil_moisture_readings
WHERE sensor_idx = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetSoilMoistureReadingsBySensorIdxParams struct {
	SensorIdx int16
	Limit     int32
}

type GetSoilMoistureReadingsBySensorIdxRow struct {
	SensorIdx int16
	Raw       int16
	CreatedAt time.Time
}

func (q *Queries) GetSoilMoistureReadingsBySensorIdx(ctx context.Context, arg GetSoilMoistureReadingsBySensorIdxParams) ([]GetSoilMoistureReadingsBySensorIdxRow, error) {
	rows, err := q.db.QueryContext(ctx, getSoilMoistureReadingsBySensorIdx, arg.SensorIdx, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSoilMoistureReadingsBySensorIdxRow
	for rows.Next() {
		var i GetSoilMoistureReadingsBySensorIdxRow
		if err := rows.Scan(&i.SensorIdx, &i.Raw, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSoilMoistureReading = `-- name: InsertSoilMoistureReading :exec
INSERT INTO soil_moisture_readings (sensor_idx, raw, created_at)
VALUES ($1, $2, $3)
`

type InsertSoilMoistureReadingParams struct {
	SensorIdx int16
	Raw       int16
	CreatedAt time.Time
}

func (q *Queries) InsertSoilMoistureReading(ctx context.Context, arg InsertSoilMoistureReadingParams) error {
	_, err := q.db.ExecContext(ctx, insertSoilMoistureReading, arg.SensorIdx, arg.Raw, arg.CreatedAt)
	return err
}
