version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: goapp
    binary: "{{ .ProjectName }}"
    main: ./cmd/api
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

release:
  prerelease: auto
  name_template: "Release {{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

universal_binaries:
  - id: goapp
    replace: true

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE*
      - frontend/public/**

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256