[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 1000000

lib_deps =
    knolleary/PubSubClient @ ^2.8
    4-20ma/ModbusMaster @ ^2.0.1

platform_packages =
    platformio/tool-clangtidy@^1.190100.0

check_tool = clangtidy

; FORCE PlatformIO to use your exact checks
check_flags =
    clangtidy: --config-file=.clang-tidy

check_src_filters =
    +<src/>
    +<include/>
    +<lib/>

check_skip_packages = yes

build_unflags =
    -std=gnu++11
    -std=gnu++14

build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3  ; 0=None 1=Error 2=Warn 3=Info 4=Debug 5=Verbose

[env:native]
platform = native
test_framework = unity
build_src_filter = -<*>

check_src_filters =
    +<test/>
    -<src/>
    +<lib/>

check_flags =
    cppcheck: --suppress=unusedFunction