[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 1000000

lib_deps =
    knolleary/PubSubClient @ ^2.8
    4-20ma/ModbusMaster @ ^2.0.1

platform_packages =
    platformio/tool-clangtidy@^1.190100.0

check_tool = clangtidy

; FORCE PlatformIO to use your exact checks
check_flags =
    clangtidy: --config-file=.clang-tidy

check_src_filters =
    +<src/>
    +<include/>

check_skip_packages = yes
test_ignore = *

[env:native]
platform = native
test_framework = unity