server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name mqtt.admission-help.org;

    ssl_certificate     /etc/letsencrypt/live/admission-help.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admission-help.org/privkey.pem;

    return 444;
}